# Hyperparameter overrides tuned for very small custom datasets.
lr0: 0.0025        # initial learning rate
lrf: 0.15          # final OneCycleLR learning rate fraction
momentum: 0.93
weight_decay: 0.0005
warmup_epochs: 1.0
warmup_momentum: 0.6
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
label_smoothing: 0.05
mixup: 0.0
mosaic: 0.1
copy_paste: 0.0
hsv_h: 0.015
hsv_s: 0.5
hsv_v: 0.35
degrees: 0.0
translate: 0.08
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
